# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74c3b7b1f06abe2b89f388088309039e8ca6410ab80d39d715b23d8249a460fb30e6ffa9711158257e8abcdfca94291e304d81acd795cbde51b67a7fc4a97ef

test:
  secret_key_base: 82b815fcac29816b13934a6c58328f38036c35366e2320f34f29e66a7214adc04738d8416535d3e4526df4b37adcde16cff6f768d068a4d6ba43327bdc8e37e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
